### ISSUE TITLE
Create keyspace on startup through docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by pankaj-dahiya** [docker-library/cassandra#182] opened 2019-06-18 12:30 UTC
This is a feature request (already request by many, manytimes),

Please provide a feature, through which .cql files will directly execute through copying them into docker-entrypoint-initdb.d folder.

I knew, there are many solutions available like making our own dockerfile! but I guess, the official dockerfile must include this option.

This will help a lot!

**Comment by wglambert** [comment] 2019-06-18 16:58
Duplicate of https://github.com/docker-library/cassandra/issues/31 and https://github.com/docker-library/cassandra/issues/65

https://github.com/docker-library/cassandra/issues/31#issuecomment-426777266
>the proper deployment of Cassandra is clustered, and is _much_ more complicated to get right automatically.  It is not recommended to use a standalone deployment, and I fear such a feature would encourage folks to do so . . .

**Closed** 2019-09-06 16:34 UTC
Labels: Request
