### ISSUE TITLE
Node tool display a different DC name other than the name specified by CASSANDRA_DC

### ISSUE THREAD

**Issue by JackeyLee007** [docker-library/cassandra#66] opened 2016-05-26 04:10 UTC
Event run with "-e CASSANDRA_DC <dc_name>" and the cassandra-rackdc.properties file store the right dc_name, the "nodetool info" command still shows "Data Center: datacenter1"

**Comment by yosifkit** [comment] 2016-05-26 16:01
duplicate of #57.

**Closed by yosifkit** 2016-05-26 16:01 UTC
