### ISSUE TITLE
Create schema

### ISSUE THREAD

**Issue by DavidRG13** [docker-library/cassandra#65] opened 2016-05-23 14:52 UTC
Hi everyone,

Is there any "standard" way of creating a schema? Or should I write my own Dockerfile/Entrypoint?

Thank you!

**Comment by varadharajan** [comment] 2017-02-15 10:40
I came across the MySQL [entry point file](https://github.com/docker-library/mysql/blob/b4b7c8eea0690d0406a5ffc2d3404c8c42457a2d/5.6/docker-entrypoint.sh#L169) and i would prefer something like that.

**Comment by shankarshastri** [comment] 2018-06-08 13:46
```
cassandra:
    image: cassandra
    ports:
    - "9042:9042"
    - "9160:9160"
    hostname: cassandra
    container_name: cassandra
    volumes:
      - ./random_path/random.cql:/tmp/random.cql
    command: >
            bash -c "((sleep 20s && cqlsh < /tmp/random.cql &) 
            && (/docker-entrypoint.sh cassandra -f)"
```
I did it like this with docker-compose.yml
In case of normal docker, we may need to wait for cassandra to come up. And once it's up, then you may need to exec into the docker container using
```
docker cp /random_path/random.cql cassandra:/tmp/random.cql
docker exec -i cassandra bash -c "cqlsh < /tmp/random.cql"
```
Or  you can mount the cql files before as shown above in docker-compose.yml file.
And then run exec commands.

**Comment by awalterschulze** [comment] 2018-06-08 14:06
We currently use this:
https://gist.github.com/awalterschulze/7732a15b555facdd9399b7f8ed9b88bf
I hope someone else can come up with something better using two phase build to build the populated schema database into the single docker.

**Comment by tianon** [comment] 2018-09-20 22:30
Duplicate of https://github.com/docker-library/cassandra/issues/31.

**Closed by tianon** 2018-09-20 22:30 UTC
Labels: Request, question
